# Generated by Django 3.2.9 on 2021-12-09 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_booking', models.IntegerField(null=True)),
                ('total', models.FloatField(null=True)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_lastname', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('customer_tel', models.CharField(max_length=15, null=True)),
                ('customer_special_req', models.CharField(max_length=250, null=True)),
                ('option_pay', models.CharField(max_length=25, null=True)),
                ('hour_arrive', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('nro_personas', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
