# Generated by Django 3.2.9 on 2021-12-11 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 0, 34, 7, 867461)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 0, 34, 7, 867461)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nro_personas',
            field=models.IntegerField(default=2),
        ),
    ]
