# Generated by Django 3.2.9 on 2021-12-11 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211211_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lst_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_desc_type',
            field=models.CharField(choices=[('matrimonial', 'Matrimonial - S/ 120.00'), ('doble', 'Doble - S/ 160.00'), ('suite', 'Libre - S/ 160.00')], default='matrimonial', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 15, 32, 55, 458579, tzinfo=utc)),
        ),
    ]
