# Generated by Django 3.2.9 on 2021-12-28 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211211_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=datetime.date(2021, 12, 28)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=datetime.date(2021, 12, 29)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lst_price',
            field=models.FloatField(choices=[(120, 'S/ 120.00'), (160, 'S/ 160.00')], default=160),
        ),
        migrations.AlterField(
            model_name='booking',
            name='option_pay',
            field=models.CharField(choices=[('reservacion', 'Solo reservar'), ('transferencia', 'Cta cci banco Interbank'), ('visa', 'Pago en línea')], default='reservacion', max_length=25),
        ),
    ]
